// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(schema, options) {
    var uuid;
    uuid = require('node-uuid');
    schema.add({
      active: {
        type: Boolean,
        "default": false
      },
      activated_at: {
        type: Date
      },
      activation_token: {
        type: String
      }
    });
    schema.pre('save', function(next) {
      if (!this.activation_token) {
        this.activation_token = uuid.v1();
      }
      return next();
    });
    return schema.methods.activate = function(callback) {
      this.active = true;
      this.activated_at = new Date();
      return this.save(callback);
    };
  };

}).call(this);
